[package]
name = "ising"
version = "0.1.2"
authors = ["Lucas Rooyakkers <lucas.rooyakkers@protonmail.com>"]
edition = "2024"
description = "Simulate the 2D Ising model with the Metropolis algorithm."
license = "GPL-3.0-or-later"
repository = "https://github.com/Fierthraix/ising-rs"

[dependencies]
rand = "0.10.1"
lazy_static = "1.5"
structopt = "0.3.26"
png = "0.18.1"
