[package]
name = "ising"
version = "0.1.0"
authors = ["Lucas Rooyakkers <lucas.rooyakkers@protonmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.4"
lazy_static = "1.4"
structopt = "0.3.23"
png = "0.17.2"
